# FamilyFeud main config
# This file will grow as features are added
# surveys here are examples

host-permission: "familyfeud.host"   # perms to control host UI/actions
allow-chat-guesses: false            # eh, chat guesses are a bit of a wildcard, so this is a toggle, host descretion for now
max-strikes: 3

surveys:
  example_animals:
    question: "Name a farm animal"
    answers:
      - text: "Cow"
        points: 35
        aliases: ["Cattle"]
      - text: "Pig"
        points: 20
      - text: "Chicken"
        points: 15
      - text: "Horse"
        points: 10
      - text: "Sheep"
        points: 8
      - text: "Goat"
        points: 6
  example_breakfast:
    question: "Name a popular breakfast food"
    answers:
      - text: "Eggs"
        points: 30
      - text: "Pancakes"
        points: 25
      - text: "Bacon"
        points: 20
      - text: "Cereal"
        points: 15
      - text: "Toast"
        points: 10
